Vue
digitalbazaar/bedrock-views pull request #37
Opened 2018-07-28 02:55 UTC by dlongley

2018-08-03 21:36 UTC, davidlehn commented on CHANGELOG.md
> +
Needs more info: adding vue, breaking changes, etc

2018-08-03 21:37 UTC, davidlehn commented on lib/vue-sfc-compiler.js
> +const logger = bedrock.loggers.get('app').child('bedrock-views');
Could extract common logger to local logger.js like in other modules.

2018-08-03 21:47 UTC, davidlehn commented on lib/config.js
> +config.views.less.compile.order = [/*'bootstrap', 'font-awesome'*/];
may be able to remove this.  similar font-awesome code below.

2018-08-03 21:51 UTC, davidlehn commented on lib/packages.js
> +    'Not Found.', 'NotFound', {'public': true, httpStatusCode: 400});
Should be 404?

2018-08-03 22:02 UTC, davidlehn commented on lib/system/plugin-vue-loader.js
> +    const error = await response.json();
Not sure how comprehensive this non-200 path needs to be.  Could get errors that throw while trying to create the message to throw.

2018-08-03 22:05 UTC, davidlehn commented on lib/vue-sfc-compiler.js
> +    write: ['compile', (results, callback) => {
Should this dependy on emptyDir too?

2018-08-03 22:53 UTC, mattcollier requested changes

2018-08-03 22:53 UTC, mattcollier commented on lib/system/plugin-vue-loader.js
> +/* global System, URL, fetch */
these globals could be defined in an .eslintrc file in this subdir that specifies an appropriate environment or globals like this: https://github.com/digitalbazaar/bedrock-ledger-agent/blob/master/test/mocha/.eslintrc#L5

2018-08-03 22:53 UTC, mattcollier commented on lib/vue-sfc-compiler.js
> +const bedrock = require('bedrock');
license, copyright, strict?

2018-08-03 22:53 UTC, mattcollier commented on lib/vue-sfc-compiler.js
> +const BedrockError = bedrock.util.BedrockError;
destructured assignment.

2018-08-03 22:53 UTC, mattcollier commented on lib/vue-sfc-compiler.js
> +              // disable babel, unnecessary overhead
what is going on here?  remove? fix comments?

2018-08-03 22:53 UTC, mattcollier commented on lib/vue-sfc-compiler.js
> +          'public': true,
remove quotes.

2018-08-03 22:53 UTC, mattcollier commented on lib/vue-sfc-compiler.js
> +        if(filename === dep) {
is `err` when `filename !== dep` being handled properly?  If so, a comment would be helpful.

2018-08-06 18:31 UTC, davidlehn approved these changes

2018-08-06 18:37 UTC, merged